zuul.d/layout.yaml

Allows us to move custom jobs to molecule projects.

Temporary disable custom jobs

---

zuul.d/layout.yaml

Reactivates Zuul CI jobs that we disabled in order to move them inside molecule project.

Reactivate jobs after their migration

---

zuul.d/layout.yaml

Since molecule commit "Make py36 minimal version needed for running molecule"
(cd223688e14b2), python 2.7 and centos 7 are not supported anymore by molecule.
So, kill testing for this platform.

zuul.d/layout.yaml: Remove python 2.7 centos 7 tests

---

molecule_vagrant/modules/vagrant.py
molecule_vagrant/test/functional/test_func.py
molecule_vagrant/test/scenarios/molecule/vagrant_root/converge.yml
molecule_vagrant/test/scenarios/molecule/vagrant_root/molecule.yml
molecule_vagrant/test/scenarios/molecule/vagrant_root/verify.yml

vagrant does a lot of thing according to its working directory, like
reading the Vagrantfile, launching external commands, etc...
Since vagrant is started by python-vagrant, itself started by ansible
in the directory containing the create/destroy/... test playbooks, it means
that the current directory is something like $PYTHONDIR/molecule_vagrant/playbooks/
and not the molecule ephemeral directory.
In order to make sure that vagrant finds its files, the code is using
VAGRANT_CWD environment variable, which allows vagrant to work but it
doesn't change the current directory. For libvirt, it's not a problem but
for virtualbox, it will create files in this current directory. Writing
to this directory may even be forbidden.
Change the code to set the 'root' parameter of the vagrant class, …

Fix vagrant working directory

---

molecule_vagrant/modules/vagrant.py

This fixes a bug where the params for `config_options` and `provider_options` were not being merged in the `_get_vagrant_config_dict` function
Manually tested this with my remote Libvirt setup.

allowing merge_dict calls to correctly update the main dict

---

tools/test-setup.sh
tox.ini

Theses two commit should fix the current CI issues on centos8 devel. The second commit
is possibly an issue inside molecule (which should be debugged) but it's better not to wait for a fix and fix our definition on MOLECULE_NO_LOG here.

Testsuite devel fixes

---

molecule_vagrant/test/functional/test_func.py
molecule_vagrant/test/scenarios/molecule/config_options/converge.yml
molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/config_options/verify.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/converge.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/verify.yml

This pull request depends on https://github.com/ansible-community/molecule-vagrant/pull/16 since it's the missing test cases for the two bugs fixed by it.
This means that:
- the test will fail now but will have to be triggered again once the other pull request is merged
- it should not be merged now (hopefully, the CI will prevent that)

Add tests for config_options and provider_options

---

zuul.d/layout.yaml

devel is known to break from time to time and is (at the time of
writing) broken to due a yet-to-be-solved ansible bug.
For instance :
https://6814780d297d9a6f6939-900359be549f0bf1af453961f6c3712c.ssl.cf1.rackcdn.com/2715/aae50fab5869d7e05bb20204060689023dd65382/check/molecule-tox-devel-functional/32d4a18/job-output.html#l1462
So, run the tests but don't make them blocking / vote. This partially revert 4ec068d2f7e8af6c3a9b0f85675c2603fd1211a5

zuul.d/layout.yaml: Make devel non voting

---

molecule_vagrant/playbooks/create.yml
molecule_vagrant/playbooks/destroy.yml

Fix the vagrant provider name so that if no value is defined or empty value provided the default value for the driver is used.
For example the below doesn't work
```
...
driver:
name: vagrant
platforms:
...
```
But the example the below does
```
...
driver:
name: vagrant
provider:
name: virtualbox
platforms:
...
```

Fix the vagrant provider name if no value is defined or empty value provided

---

molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/vagrant_root/molecule.yml

True is a shell command and not an executable on some platforms.
For example on MacOS /bin/true does not exist.

Avoid unportable /bin/true

---

molecule_vagrant/modules/vagrant.py

Since molecule commit "Avoid parallel execution of a specific schenario"
(65ccd6b), the molecule scenario directory is protected by a lock.
Which is fine. Except that the vagrant module is using molecule.config.Config
to get:
- the molecule ephemeral directory,
- path to the Vagrantfile.
This will result in the vagrant module trying again to get the lock help
by molecule and fails with messages like:
Retrying to acquire lock on /home/zuul/.cache/molecule/scenarios/config_options, waiting for 30 seconds
Retrying to acquire lock on /home/zuul/.cache/molecule/scenarios/config_options, waiting for 60 seconds
Retrying to acquire lock on /home/zuul/.cache/molecule/scenarios/config_options, waiting for 90 seconds
Retrying to acquire lock on /home/zuul/.cache/molecule/scenarios/config_options, …

Avoid depending on molecule.config

---

molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/multi-node/molecule.yml
tools/test-setup.sh

This PR contains tweaks to the CI configuration. It's mostly what was in PR44. The qemu fallback patches will be in a different PR.
Important parts are containing:
- synced_folder configuration settings. Got some issues with that with the tests, so force it to use rsync instead of nfs
- change ansible gathering to explicit to speed things up
- change test devel configuration in order to have it run again (even if we know that the test will still fail due to the lock issue)

Improve CI testing

---

.github/workflows/tox.yml

This enables github integration, which also uncovers that current testing does not work on MacOS due
to the network driver being used.

Enable github action integration

---

tox.ini

This change should display the output from functional testing in real time, as this may prove important for CI testing too.

Disabled pytest capture

---

zuul.d/layout.yaml

We will be using github actions for the release pipelines and keep zuul only for testing linux compatibility.

Remove zuul pypi template

---

zuul.d/layout.yaml

- make all testing jobs voting
- enable two retries for them, as we still get hosts w/o virtualization support.

zuul: make jobs voting

---

molecule_vagrant/modules/vagrant.py
molecule_vagrant/test/scenarios/molecule/default/molecule.yml

This should allow user to disable linked_clone feature.
Based on original PR from https://github.com/ansible-community/molecule-vagrant/pull/45 made by @jpmat296

Allow linked_cloned to be disabled

---

molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/verify.yml

This nic should make testing more portable. Clearly it makes the Github actions pass all tests on MacOS, for the first time.

Switch testing nic to e1000

---

README.rst
zuul.d/layout.yaml

Due to lack of support from Vagrant for CentOS 8 we disable testing on that platform and document it. Some power users may be able to get it going but the level of hacking involved makes not suitable for any production environments.
https://github.com/hashicorp/vagrant/issues/11020
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1127

Document Vagrant being unsupported on CentOS 8

---

.github/workflows/tox.yml
setup.cfg
tox.ini

We run GitHub CI testing with both minimal an maximal versions of supported Python.

Enable testing with py36 and py39

---

.github/workflows/tox.yml
setup.cfg
tox.ini

Adopts same tox env testing setup as other drivers.

Consolidate devel testing

---

.pre-commit-config.yaml
molecule_vagrant/driver.py
setup.cfg
tox.ini

Related: https://github.com/ansible-community/molecule/pull/2926

Drop ansible as a direct dependency

---

molecule_vagrant/modules/vagrant.py

- Make sure that up() is exiting with either exit_json() or fail_json()
- Catch errors for calls to vagrant.conf() and vagrant.status()
- Now that the functions up/destroy/halt of the VagrantClient class
should all be exiting with proper fail/exit_json, but in the case of
the last line of main() is still reached, change the code to use
VagrantClient result to avoid the following exception:
AttributeError: 'AnsibleModule' object has no attribute 'result'

molecule_vagrant/modules/vagrant.py: Improve error handling

---

molecule_vagrant/modules/vagrant.py
tools/Vagrantfile

When TCG is used instead of KVM, libvirt defaults to using the EPYC
cpu model on some systems (even if the host is an intel cpu). This
leads to some weird issues, like ssh-keygen -A hanging at the
boot of alpine VM in the CI.
In previous works, I've work arounded the issue by switching the VM to
using centos instead of alpine but I think it's a good idea to
provide good working default, so the vCPU model is set to qemu64
when TCG is used, if the vCPU model is not specified.
The tools/Vagrantfile has been updated to match this vCPU model too.
Side-note: I'm still wondering if the same thing should be done for
systems without KVM, aka automatically default to TCG in this case.

Manually set cpu to qemu64 with qemu driver

---

molecule_vagrant/test/functional/test_func.py

Molecule 3.2.0a1 moved run_command to molecule.util, so update the
test code to reflect that.

Fix run_command import due to move

---

molecule_vagrant/modules/vagrant.py

In commit "Set cpu to qemu64 with qemu driver", defined?() has been
used to check if provider['options']['driver'] is defined but it seems
that the test is not doing what I was expecting. Switching to .has_key?
is fixing the issue.
Fix: #88 

Fix libvirt option driver test

---

README.rst
molecule_vagrant/driver.py
molecule_vagrant/modules/vagrant.py
molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
molecule_vagrant/test/scenarios/molecule/vagrant_root/molecule.yml

molecule_vagrant/modules/vagrant.py: Kill vagrant.yml
Using a vagrant.yml file to store the instance configuration
is adding an useless overhead and make things harder to debug.
While moving the Vagrantfile generation to use only jinja2 templating,
remove the hardcoded vagrant provider handling, since only vmware
providers are different (cpu and memory are 'vmx['numvcpus']' and
vmx['memsize']).
The new way of generating vagrant configuration will also ease to
improve the multiplatform support.
Notes:
- special vagrant-vbguest handling with virtualvbox provider removed
- to remain "bug" compatible for now, things like nic_model_type: '"e1000"'
are still working, even if the new way is nic_model_type: e1000 (or "e1000").
This will maybe vanish with multiplatform, since it'll probably …

Vagrant yaml removal

---

molecule

Current link is pointing ../molecule-vagrant/..., which is working
nicely with a clone of the project, but if the clone is done to a
directory, say bug99999, the link will be broken.
I'm not sure what's the exact purpose of this link but I'm using it a
lot to run CI test scenarii and changing the link everytime is painful.

molecule: Make link point to molecule_vagrant/test/scenarios/molecule/

---

molecule_vagrant/test/functional/test_func.py

Since https://github.com/ansible-community/molecule/pull/3195, molecule pytest
helpers are gone, so remove the code using them to use directly the molecule_directory()
function.

Remove molecule pytest helpers

---

tools/Vagrantfile
tools/test-setup.sh

This patchset is trying to make testing with Zuul CI working again. The tests are failing
as they're running inside a VM with 1G and things like the VM used to create the test box
is asking 2048M, which fails.
Reducing things to 512M should make things working again but an extra swap file is also
added to help in case the memory pressure is still too much.

Testbox memory

---

README.rst
molecule_vagrant/playbooks/create.yml
molecule_vagrant/playbooks/destroy.yml

This PR:
- replaces VBox with VirtualBox
- closes #115 
- is related to #91  
- helps slow folks like me understand the examples

Spell out VirtualBox

---

setup.cfg

The vagrant module is using Jinja2 boolean test and it's available for
2.11+ only, so ensure this minimal version is installed.

Ensure jinja2 >= 2.11

---

tox.ini

The devel test suite is failing due to trying to use the 'master'
branch, which is now called 'main'. Update tox.ini accordingly.

tox.ini: Molecule has renamed its master branch

---

molecule_vagrant/test/functional/test_func.py

The testing is failing due to ansible-lint complaining about meta/main.yml
and test role being 'test-init', so not matching any fqrn.
Instead of trying to fix the meta/main.yml, take inspiration from what
has been done for molecule-podman.
To keep changes minimal, the scenario name has been kept to 'test-scenario'.
This lead to molecule init scenario command complaining that there's no
'default' scenario, so create an empty 'molecule/default' scenario directory
to workaround that.

Fix testing error due to invalid role name

---

molecule_vagrant/modules/vagrant.py

Make `_created()` return a `bool`. If you want the state, just call `_status()`.
`state` can be `preparing` or `shutoff`, and still `_created()` should return `True`. Otherwise, a stopped machine won't be destroyed with `molecule destroy`.
I also added `_running()`, which properly tells if the VM is running. It is used for calling `up()`. Otherwise, a stopped machine won't be started before testing.

fix: false negatives for _created()

---

.github/workflows/tox.yml
.pre-commit-config.yaml
molecule_vagrant/test/scenarios/molecule/network/molecule.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/verify.yml
tools/tox-py38/pre.yml
tools/tox-py39/pre.yml
zuul.d/layout.yaml

Since https://github.com/ansible/ansible-zuul-jobs/commit/472249173a10a53e6924f4df772cd993bce439e4,
the ansible-tox-py38 job is relying on centos-8-stream and tries to
install python38-devel.
Here, we're using fedora in order to test molecule-vagrant with
distribution packages and libvirt. And trying to install python38-devel
is failing since there's no python38-devel.
While I'm going to create a branch in my fork of with fixes for centos-8-stream,
it's a pain to use since it needs the workaround for krb5 and a new
workaround for libssh. The real fix would be hashicorp to fix their broken
RPMs but looks like months (years?) and bug reports are not enough
to get them fix this.
The other possibility would have been to use fedora and py39 but there's
no ansible-tox-py39 ATM.
Signed-off-by: …

Fix several CI failures

---

tox.ini

Newer env var name caused undesired runtime warnings, so we
avoid running with custom callbacks during testings.

Avoid custom callback during testing

---

setup.cfg
tox.ini

Remove ansible extra as it was producing incompatibilities with
newer versions of ansible, which had different package names.
Out module will no longer list ansible as a dependency.

Drop ansible extra dependency

---

.github/workflows/tox.yml

To lower the chance of hitting "MacOs concurrency limits" on GHA,
we use linux for jobs that do not really need macos.

Avoid using macos runners when not needed

---

.github/workflows/tox.yml

Reduce number of macos workers from 4 to 2 by running devel testing
just after non-devel ones.

Chain GHA devel test runs

---

setup.cfg

As of today the oldest version of molecule still supported is 3.4.1,
and we want to be sure this driver is no used with versions older
than this.
This is also fixing a serious bug that made pip use pre-release versions. We should never make use of pre-release versions inside dependencies.

Require molecule >= 3.4.1

---

tox.ini

This fixes py39 execution on Fedora where we needed a newer pip to perform editable installs.

Bump tox/pip used during testing

---

tools/create_testbox.sh

With GHA caching the testbox may already be there so trying to add
a new testbox will fail, to exit early in this case.
Also make sure there's no testbox.box file in the current directory,
even if this should not happen in the CI theorically.

tools/create_testbox.sh: Don't create test box if already available

---

tools/test-setup.sh
tools/tox-py39/pre.yml

btrfs does not support swapfile. With a loopback device, we bypass the
limitation.

swapon: use a loopback device

---

molecule_vagrant/modules/vagrant.py

vagrant-vsphere uses its own way of configuring memory and number of cpus. This needs to be reflected in the template for the Vagrantfile

Add support for vagrant-vsphere memory and cpu

---

.github/workflows/tox.yml
molecule_vagrant/modules/vagrant.py
molecule_vagrant/test/functional/test_func.py
molecule_vagrant/test/scenarios/molecule/invalid/converge.yml
molecule_vagrant/test/scenarios/molecule/invalid/molecule.yml
setup.cfg

python-vagrant 1.0.0 adds a new validate() function, so use it
instead of the open coded version here. [ So, bump minimal version
to 1.0.0 ].
While at it, add a small test case for it to make sure it's handled
properly as I managed to get it wrong in my first version of this
patch.

Add validate() implementation

---

molecule_vagrant/playbooks/create.yml
molecule_vagrant/test/scenarios/molecule/default-compat/create.yml

Fixes the following errors:
- unnamed-task by adding a "name:" to the task
- no-handler: I'm not sure it's really interesting to convert
it to an handler so just silence the warning.
There's still a schema error but it's will be fixed by ansible-lint
schema update [ https://github.com/ansible/schemas/commit/795989e7950c7412e184e2aae93dcf33710544d4 ].

create.yml: Fix ansible-lint 6.3.0 errors in task writing instances cfg

---

.github/workflows/tox.yml
README.rst
molecule_vagrant/modules/vagrant.py
molecule_vagrant/test/functional/test_func.py
molecule_vagrant/test/scenarios/molecule/hostname/converge.yml
molecule_vagrant/test/scenarios/molecule/hostname/molecule.yml
molecule_vagrant/test/scenarios/molecule/hostname/verify.yml
tools/test-setup.sh

It may be useful to be able to set the instance hostname/FQDN or to prevent
vagrant to set the hostname, so add support for that.
The default behaviour is unchanged: the host name is set to the instance
name.
Fixes: #157

Allow setting instance host name

---

molecule_vagrant/test/scenarios/molecule/config_options/converge.yml
molecule_vagrant/test/scenarios/molecule/default-compat/converge.yml
molecule_vagrant/test/scenarios/molecule/default/converge.yml
molecule_vagrant/test/scenarios/molecule/hostname/converge.yml
molecule_vagrant/test/scenarios/molecule/invalid/converge.yml
molecule_vagrant/test/scenarios/molecule/multi-node/converge.yml
molecule_vagrant/test/scenarios/molecule/multi-node/verify.yml
molecule_vagrant/test/scenarios/molecule/network/converge.yml
molecule_vagrant/test/scenarios/molecule/provider_config_options/converge.yml
molecule_vagrant/test/scenarios/molecule/vagrant_root/converge.yml
molecule_vagrant/test/scenarios/molecule/vagrant_root/verify.yml

This PR:
- removes `warn:` from `command:` and `shell:` tasks, the feature is deprecated for `command:` (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#parameter-warn)

remove warn from shell and command tasks

---

README.rst
molecule_vagrant/playbooks/create.yml
molecule_vagrant/playbooks/destroy.yml
molecule_vagrant/test/scenarios/molecule/default-compat/create.yml
tools/Vagrantfile

This PR:
- replaces the generic/alpine310 box with generic/alpine316, this because Alpine 3.10 has been EOL since 2021-05-01

Re-post: use generic/alpine316

---

.github/workflows/release.yml
.github/workflows/tox.yml
requirements.txt

This PR:
- Updates the GitHub actions, since Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
- Closes #200 

Update GH actions

---

pyproject.toml

pyproject.toml:
Update build-system requirements for setuptools-scm to >= 7.0.0, which obsoletes setuptools-scm-git-archive.
Remove wheel, as it is not required in a PEP517 build environment facilitating pypa/build and pypa/installer.

Update build-system requirements for setuptools-scm to >= 7.0.0

---

molecule_vagrant/playbooks/create.yml
molecule_vagrant/playbooks/destroy.yml
molecule_vagrant/test/scenarios/molecule/default-compat/create.yml
molecule_vagrant/test/scenarios/molecule/default-compat/destroy.yml

The local vagrant module is not (yet?) inside a collection, so there's no FQCN. Add needed noqa bits.

Silence ansible fqcn error about vagrant module.

---

.github/workflows/tox.yml

Missed a old action, replaced with `actions/setup-python@v4`

use actions/setup-python@v4
